import type { Dialect } from './types';

export interface ExampleEntry {
  /** Rule name exactly as the solid-checker catalog spells it. */
  rule: string;
  /** Directory under `examples/<dialect>/` holding `incorrect.tsx` and `correct.tsx`. */
  dir: string;
  /** Stable diagnostic code the finding carries. */
  code: string;
  severity: 'error' | 'warning';
  /** Group heading in the picker. */
  category: string;
  /** One sentence describing the defect the incorrect file contains. */
  summary: string;
  /**
   * Codes the incorrect file reports in addition to `code`. The defect it shows
   * genuinely belongs to more than one rule, so both findings are expected.
   */
  alsoReports?: readonly string[];
  /**
   * Set when a single playground file cannot reproduce the finding, because the
   * rule needs a project shape the playground does not have (a second package,
   * a stale fact producer). The example then documents the rule instead of
   * triggering it, and the picker says so.
   */
  standalone?: false;
  /**
   * Set when the incorrect file also draws a TypeScript error, because the only
   * shape a single file can use to trigger the rule is one tsc also rejects.
   */
  alsoTypeError?: true;
}

const trackingV2 = 'Tracking & component semantics';
const jsxV2 = 'JSX correctness';
const writesV2 = 'Writes & actions';
const leafV2 = 'Leaf owners & cleanup';
const ownershipV2 = 'Ownership';
const asyncV2 = 'Async';
const directivesV2 = 'Directives';
const shapesV2 = 'API shapes';
const limitsV2 = 'Analysis limits (uncertifiable)';

export const SOLID_V2_EXAMPLES: readonly ExampleEntry[] = [
  {
    rule: 'strict-read-untracked',
    dir: 'strict-read-untracked',
    code: 'SC1001',
    severity: 'warning',
    category: trackingV2,
    summary: 'A prop is read at the top of a component body, so it is captured once and never updates.',
  },
  {
    rule: 'reactive-read-after-await',
    dir: 'reactive-read-after-await',
    code: 'SC1002',
    severity: 'error',
    category: trackingV2,
    summary: 'A reactive value is read after an await, where tracking has already ended.',
  },
  {
    rule: 'component-props-destructure',
    dir: 'component-props-destructure',
    code: 'SC1003',
    severity: 'error',
    category: trackingV2,
    summary: 'Props are destructured, which unwraps the reactive object into frozen locals.',
  },
  {
    rule: 'component-returns-conditionally',
    dir: 'component-returns-conditionally',
    code: 'SC1004',
    severity: 'error',
    category: trackingV2,
    summary: 'A component returns from more than one place, so the branch is decided once at setup.',
    alsoReports: ['SC1001'],
  },
  {
    rule: 'uncalled-accessor',
    dir: 'uncalled-accessor',
    code: 'SC1005',
    severity: 'warning',
    category: trackingV2,
    summary: 'An accessor is used as a value without being called, so the function object is consumed.',
  },
  {
    rule: 'untracked-derived-function',
    dir: 'untracked-derived-function',
    code: 'SC1006',
    severity: 'warning',
    category: trackingV2,
    summary: 'A derived function is called from a scope that tracks nothing, so its reads never subscribe.',
  },
  {
    rule: 'expected-function-got-expression',
    dir: 'expected-function-got-expression',
    code: 'SC1007',
    severity: 'warning',
    category: trackingV2,
    summary: 'A handler position whose contract is a function receives a reactive expression instead.',
  },
  {
    rule: 'prefer-component-syntax',
    dir: 'prefer-component-syntax',
    code: 'SC8018',
    severity: 'warning',
    category: jsxV2,
    summary: 'A lowercase JSX-returning function is called as an expression instead of rendered as a component.',
  },
  {
    rule: 'no-implicit-draggable',
    dir: 'no-implicit-draggable',
    code: 'SC8019',
    severity: 'error',
    category: jsxV2,
    summary: 'draggable={false} on a draggable-by-default element removes the attribute and re-enables dragging.',
  },
  {
    rule: 'valid-jsx-nesting',
    dir: 'valid-jsx-nesting',
    code: 'SC8020',
    severity: 'error',
    category: jsxV2,
    summary: 'The HTML parser rewrites this nesting, so the authored tree is not the tree that hydrates.',
  },
  {
    rule: 'reactive-write-in-owned-scope',
    dir: 'reactive-write-in-owned-scope',
    code: 'SC2001',
    severity: 'error',
    category: writesV2,
    summary: 'A signal is written under a children-capable owner, which throws in dev.',
  },
  {
    rule: 'action-called-in-owned-scope',
    dir: 'action-called-in-owned-scope',
    code: 'SC2002',
    severity: 'error',
    category: writesV2,
    summary: 'An action is started during component setup instead of from an imperative boundary.',
  },
  {
    rule: 'no-direct-mutation',
    dir: 'no-direct-mutation',
    code: 'SC2003',
    severity: 'warning',
    category: writesV2,
    summary: 'A reactive value is mutated in place, so the write is dropped and nothing is notified.',
  },
  {
    rule: 'resolve-in-reactive-scope',
    dir: 'resolve-in-reactive-scope',
    code: 'SC2004',
    severity: 'error',
    category: writesV2,
    summary: 'resolve() is called while an observer is active, which throws in dev.',
  },
  {
    rule: 'cleanup-in-forbidden-scope',
    dir: 'cleanup-in-forbidden-scope',
    code: 'SC3001',
    severity: 'error',
    category: leafV2,
    summary: 'onCleanup is called inside a leaf owner, which cannot own children.',
  },
  {
    rule: 'primitive-in-leaf-owner',
    dir: 'primitive-in-leaf-owner',
    code: 'SC3002',
    severity: 'error',
    category: leafV2,
    summary: 'An owner-attaching primitive is created inside a leaf owner, which throws in dev.',
  },
  {
    rule: 'flush-in-forbidden-scope',
    dir: 'flush-in-forbidden-scope',
    code: 'SC3003',
    severity: 'error',
    category: leafV2,
    summary: 'flush() is called from inside the flush cycle it would drive.',
  },
  {
    rule: 'no-owner-effect',
    dir: 'no-owner-effect',
    code: 'SC4001',
    severity: 'warning',
    category: ownershipV2,
    summary: 'An effect is created where no owner exists, so nothing will ever dispose it.',
  },
  {
    rule: 'no-owner-cleanup',
    dir: 'no-owner-cleanup',
    code: 'SC4002',
    severity: 'warning',
    category: ownershipV2,
    summary: 'onCleanup runs without an owner, so the teardown is never registered.',
  },
  {
    rule: 'no-owner-boundary',
    dir: 'no-owner-boundary',
    code: 'SC4003',
    severity: 'warning',
    category: ownershipV2,
    summary: 'A boundary is built outside any owner, so it and its subtree can never be disposed.',
  },
  {
    rule: 'no-owner-settled-cleanup',
    dir: 'no-owner-settled-cleanup',
    code: 'SC4004',
    severity: 'error',
    category: ownershipV2,
    summary: 'onSettled returns a cleanup where no owner can hold it, so the teardown is dropped.',
  },
  {
    rule: 'pending-async-untracked-read',
    dir: 'pending-async-untracked-read',
    code: 'SC5001',
    severity: 'error',
    category: asyncV2,
    summary: 'An async source is read untracked, which throws while the value is still pending.',
    alsoReports: ['SC1001'],
  },
  {
    rule: 'pending-async-forbidden-scope',
    dir: 'pending-async-forbidden-scope',
    code: 'SC5002',
    severity: 'warning',
    category: asyncV2,
    summary: 'A pending async value reaches a leaf owner, which cannot wait for it.',
  },
  {
    rule: 'async-outside-loading-boundary',
    dir: 'async-outside-loading-boundary',
    code: 'SC5003',
    severity: 'warning',
    category: asyncV2,
    summary: 'An async read has no Loading boundary above it, so nothing renders until it settles.',
  },
  {
    rule: 'ssr-client-source-outside-loading-boundary',
    dir: 'ssr-client-source-outside-loading-boundary',
    code: 'SC5005',
    severity: 'error',
    category: asyncV2,
    summary: 'A client-only source is read where SSR has neither a boundary fallback nor a declared first paint.',
  },
  {
    rule: 'primitive-in-directive-application',
    dir: 'primitive-in-directive-application',
    code: 'SC6001',
    severity: 'warning',
    category: directivesV2,
    summary: 'A directive creates a computation in its apply phase, which runs unowned once per element.',
  },
  {
    rule: 'missing-effect-function',
    dir: 'missing-effect-function',
    code: 'SC7001',
    severity: 'error',
    category: shapesV2,
    summary: 'createEffect is called in the Solid 1.x single-callback shape, with no apply function.',
  },
  {
    rule: 'sync-node-received-async',
    dir: 'sync-node-received-async',
    code: 'SC7002',
    severity: 'error',
    category: shapesV2,
    summary: 'A computation marked sync: true is given an async compute function.',
  },
  {
    rule: 'http-response-after-flush',
    dir: 'http-response-after-flush',
    code: 'SC7005',
    severity: 'warning',
    category: shapesV2,
    summary: 'The HTTP response head is decided below a Loading boundary, after the shell may already have flushed.',
  },
  {
    rule: 'server-function-module-directive',
    dir: 'server-function-module-directive',
    code: 'SC7006',
    severity: 'error',
    category: shapesV2,
    summary: 'Under a module-level "use server", a wrapped export is dropped from the client build.',
  },
  {
    rule: 'server-function-rich-argument',
    dir: 'server-function-rich-argument',
    code: 'SC7007',
    severity: 'error',
    category: shapesV2,
    summary: 'A server function receives an argument the plain transport cannot serialize.',
  },
  {
    rule: 'package-contract-export-missing',
    dir: 'package-contract-export-missing',
    code: 'SC9001',
    severity: 'error',
    category: limitsV2,
    summary: 'An imported export has no contract entry, so nothing flowing through it can be certified.',
    alsoReports: ['SC9011'],
    alsoTypeError: true,
  },
  {
    rule: 'execution-map-incomplete',
    dir: 'execution-map-incomplete',
    code: 'SC9004',
    severity: 'error',
    category: limitsV2,
    summary: 'The compiler left a JSX expression unclassified, so reads inside it cannot be judged.',
    standalone: false,
  },
  {
    rule: 'package-contract-missing',
    dir: 'package-contract-missing',
    code: 'SC9005',
    severity: 'error',
    category: limitsV2,
    summary: 'An imported Solid-integrating package ships no reactivity contract.',
    standalone: false,
  },
  {
    rule: 'package-contract-callback-missing',
    dir: 'package-contract-callback-missing',
    code: 'SC9006',
    severity: 'error',
    category: limitsV2,
    summary: 'A callback reaches an external helper whose execution timing no contract describes.',
    standalone: false,
  },
  {
    rule: 'reactive-source-uncaptured',
    dir: 'reactive-source-uncaptured',
    code: 'SC9011',
    severity: 'warning',
    category: limitsV2,
    summary: 'A reactive source is passed to a package function whose reactive behaviour is undescribed.',
    standalone: false,
  },
  {
    rule: 'reactive-dispatch-unresolved',
    dir: 'reactive-dispatch-unresolved',
    code: 'SC9012',
    severity: 'warning',
    category: limitsV2,
    summary: 'A call can reach implementations with different reactivity, so its behaviour cannot be pinned down.',
  },
];

const trackingV1 = 'Tracking & component semantics';
const writesV1 = 'Writes';
const leafV1 = 'Leaf owners & cleanup';
const ownershipV1 = 'Ownership';
const asyncV1 = 'Async';
const directivesV1 = 'Directives';
const shapesV1 = 'API shapes';
const eslintV1 = 'eslint-plugin-solid surface';
const limitsV1 = 'Analysis limits (uncertifiable)';

export const SOLID_V1_EXAMPLES: readonly ExampleEntry[] = [
  {
    rule: 'v1/strict-read-untracked',
    dir: 'strict-read-untracked',
    code: 'SC1001',
    severity: 'warning',
    category: trackingV1,
    summary: 'A prop is read at the top of a component body, so it is captured once and never updates.',
  },
  {
    rule: 'v1/reactive-read-after-await',
    dir: 'reactive-read-after-await',
    code: 'SC1002',
    severity: 'error',
    category: trackingV1,
    summary: 'A reactive value is read after an await, where tracking has already ended.',
    alsoReports: ['SC5004'],
  },
  {
    rule: 'v1/no-destructure',
    dir: 'no-destructure',
    code: 'SC1003',
    severity: 'error',
    category: trackingV1,
    summary: 'Props are destructured, which unwraps the reactive object into frozen locals.',
  },
  {
    rule: 'v1/components-return-once',
    dir: 'components-return-once',
    code: 'SC1004',
    severity: 'warning',
    category: trackingV1,
    summary: 'A component returns from more than one place, so the branch is decided once at setup.',
    alsoReports: ['SC1001'],
  },
  {
    rule: 'v1/uncalled-accessor',
    dir: 'uncalled-accessor',
    code: 'SC1005',
    severity: 'warning',
    category: trackingV1,
    summary: 'An accessor is used as a value without being called, so the function object is consumed.',
  },
  {
    rule: 'v1/untracked-derived-function',
    dir: 'untracked-derived-function',
    code: 'SC1006',
    severity: 'warning',
    category: trackingV1,
    summary: 'A derived function is called from a scope that tracks nothing, so its reads never subscribe.',
  },
  {
    rule: 'v1/expected-function-got-expression',
    dir: 'expected-function-got-expression',
    code: 'SC1007',
    severity: 'warning',
    category: trackingV1,
    summary: 'A handler position whose contract is a function receives a reactive expression instead.',
    alsoReports: ['SC1001'],
  },
  {
    rule: 'v1/reactive-write-in-owned-scope',
    dir: 'reactive-write-in-owned-scope',
    code: 'SC2001',
    severity: 'error',
    category: writesV1,
    summary: 'A signal is written from a component body, which feeds the graph that produced it.',
  },
  {
    rule: 'v1/no-direct-mutation',
    dir: 'no-direct-mutation',
    code: 'SC2003',
    severity: 'warning',
    category: writesV1,
    summary: 'A reactive value is mutated in place, so the write is dropped and nothing is notified.',
  },
  {
    rule: 'v1/cleanup-in-forbidden-scope',
    dir: 'cleanup-in-forbidden-scope',
    code: 'SC3001',
    severity: 'error',
    category: leafV1,
    summary: 'onCleanup is registered inside a createReaction callback, which is a leaf and never runs it.',
    alsoReports: ['SC4002'],
  },
  {
    rule: 'v1/primitive-in-leaf-owner',
    dir: 'primitive-in-leaf-owner',
    code: 'SC3002',
    severity: 'error',
    category: leafV1,
    summary: 'A primitive is created inside a createReaction callback, where it is never tracked or disposed.',
  },
  {
    rule: 'v1/no-owner-effect',
    dir: 'no-owner-effect',
    code: 'SC4001',
    severity: 'warning',
    category: ownershipV1,
    summary: 'An effect is created at module scope, so nothing will ever dispose it.',
  },
  {
    rule: 'v1/no-owner-cleanup',
    dir: 'no-owner-cleanup',
    code: 'SC4002',
    severity: 'warning',
    category: ownershipV1,
    summary: 'onCleanup runs without an owner, so the teardown is never registered.',
  },
  {
    rule: 'v1/no-owner-boundary',
    dir: 'no-owner-boundary',
    code: 'SC4003',
    severity: 'warning',
    category: ownershipV1,
    summary: 'A Suspense boundary is built at module scope, so it and its subtree can never be disposed.',
  },
  {
    rule: 'v1/no-async-tracked-scope',
    dir: 'no-async-tracked-scope',
    code: 'SC5004',
    severity: 'warning',
    category: asyncV1,
    summary: 'An async function is passed where a tracked computation is expected.',
    alsoReports: ['SC1002'],
  },
  {
    rule: 'v1/primitive-in-directive-application',
    dir: 'primitive-in-directive-application',
    code: 'SC6001',
    severity: 'error',
    category: directivesV1,
    summary: 'A use: directive creates a primitive in the per-element callback, which is an unowned leaf.',
  },
  {
    rule: 'v1/missing-effect-function',
    dir: 'missing-effect-function',
    code: 'SC7001',
    severity: 'error',
    category: shapesV1,
    summary: 'createEffect receives a first argument that is not a function.',
  },
  {
    rule: 'v1/event-handlers',
    dir: 'event-handlers',
    code: 'SC8001',
    severity: 'warning',
    category: eslintV1,
    summary: 'A declared handler is written in its all-lowercase alias instead of the canonical spelling.',
  },
  {
    rule: 'v1/jsx-no-duplicate-props',
    dir: 'jsx-no-duplicate-props',
    code: 'SC8003',
    severity: 'error',
    category: eslintV1,
    summary: 'Two differently spelled props land in the same compiler slot, so one of them is dead.',
    alsoReports: ['SC8001'],
  },
  {
    rule: 'v1/jsx-no-script-url',
    dir: 'jsx-no-script-url',
    code: 'SC8004',
    severity: 'error',
    category: eslintV1,
    summary: 'A statically known attribute value uses the javascript: URL scheme.',
  },
  {
    rule: 'v1/jsx-no-undef',
    dir: 'jsx-no-undef',
    code: 'SC8005',
    severity: 'error',
    category: eslintV1,
    summary: 'A use: directive names a binding that does not exist.',
  },
  {
    rule: 'v1/jsx-uses-vars',
    dir: 'jsx-uses-vars',
    code: 'SC8006',
    severity: 'error',
    category: eslintV1,
    summary: 'Kept for eslint-plugin-solid config compatibility; it emits no finding by design.',
    standalone: false,
  },
  {
    rule: 'v1/no-array-handlers',
    dir: 'no-array-handlers',
    code: 'SC8007',
    severity: 'error',
    category: eslintV1,
    summary: 'An event prop receives a [handler, data] bound pair, whose data is never type-checked.',
  },
  {
    rule: 'v1/no-innerhtml',
    dir: 'no-innerhtml',
    code: 'SC8008',
    severity: 'error',
    category: eslintV1,
    summary: 'innerHTML is given a dynamic value, which is an injection surface.',
  },
  {
    rule: 'v1/no-proxy-apis',
    dir: 'no-proxy-apis',
    code: 'SC8009',
    severity: 'error',
    category: eslintV1,
    summary: 'The code depends on Proxy, which cannot be polyfilled for a no-Proxy target.',
  },
  {
    rule: 'v1/no-react-deps',
    dir: 'no-react-deps',
    code: 'SC8010',
    severity: 'warning',
    category: eslintV1,
    summary: 'A React-style dependency array is passed where Solid expects an initial previous value.',
  },
  {
    rule: 'v1/no-react-specific-props',
    dir: 'no-react-specific-props',
    code: 'SC8011',
    severity: 'warning',
    category: eslintV1,
    summary: 'A component is passed className/htmlFor, which Solid never renames to class/for.',
  },
  {
    rule: 'v1/no-unknown-namespaces',
    dir: 'no-unknown-namespaces',
    code: 'SC8012',
    severity: 'error',
    category: eslintV1,
    summary: 'A namespaced prop is put on a component, where the prefix has no effect at all.',
  },
  {
    rule: 'v1/prefer-classlist',
    dir: 'prefer-classlist',
    code: 'SC8013',
    severity: 'warning',
    category: eslintV1,
    summary: 'A classnames-style object call builds the class string instead of using classList.',
  },
  {
    rule: 'v1/prefer-for',
    dir: 'prefer-for',
    code: 'SC8014',
    severity: 'error',
    category: eslintV1,
    summary: 'Array#map renders a list directly as JSX children instead of using <For>.',
  },
  {
    rule: 'v1/prefer-show',
    dir: 'prefer-show',
    code: 'SC8015',
    severity: 'warning',
    category: eslintV1,
    summary: 'Element content is rendered conditionally with && or ?: instead of <Show>.',
  },
  {
    rule: 'v1/self-closing-comp',
    dir: 'self-closing-comp',
    code: 'SC8016',
    severity: 'warning',
    category: eslintV1,
    summary: 'A childless element is written with a closing tag instead of self-closing.',
  },
  {
    rule: 'v1/style-prop',
    dir: 'style-prop',
    code: 'SC8017',
    severity: 'warning',
    category: eslintV1,
    summary: 'style is given a string, which is replaced wholesale instead of patched per property.',
  },
  {
    rule: 'v1/prefer-component-syntax',
    dir: 'prefer-component-syntax',
    code: 'SC8018',
    severity: 'warning',
    category: eslintV1,
    summary: 'A lowercase JSX-returning function is called as an expression instead of rendered as a component.',
  },
  {
    rule: 'v1/no-implicit-draggable',
    dir: 'no-implicit-draggable',
    code: 'SC8019',
    severity: 'error',
    category: eslintV1,
    summary: 'Boolean shorthand draggable serializes an empty value and selects the auto state.',
  },
  {
    rule: 'v1/valid-jsx-nesting',
    dir: 'valid-jsx-nesting',
    code: 'SC8020',
    severity: 'error',
    category: eslintV1,
    summary: 'The HTML parser rewrites this nesting, so the authored tree is not the tree that hydrates.',
  },
  {
    rule: 'v1/package-contract-export-missing',
    dir: 'package-contract-export-missing',
    code: 'SC9001',
    severity: 'error',
    category: limitsV1,
    summary: 'An imported export has no contract entry, so nothing flowing through it can be certified.',
    alsoTypeError: true,
  },
  {
    rule: 'v1/execution-map-incomplete',
    dir: 'execution-map-incomplete',
    code: 'SC9004',
    severity: 'error',
    category: limitsV1,
    summary: 'The compiler left a JSX expression unclassified, so reads inside it cannot be judged.',
    standalone: false,
  },
  {
    rule: 'v1/package-contract-missing',
    dir: 'package-contract-missing',
    code: 'SC9005',
    severity: 'error',
    category: limitsV1,
    summary: 'An imported Solid-integrating package ships no reactivity contract.',
    standalone: false,
  },
  {
    rule: 'v1/package-contract-callback-missing',
    dir: 'package-contract-callback-missing',
    code: 'SC9006',
    severity: 'error',
    category: limitsV1,
    summary: 'A callback reaches an external helper whose execution timing no contract describes.',
    standalone: false,
  },
  {
    rule: 'v1/reactive-source-uncaptured',
    dir: 'reactive-source-uncaptured',
    code: 'SC9011',
    severity: 'warning',
    category: limitsV1,
    summary: 'A reactive source is passed to a package function whose reactive behaviour is undescribed.',
    standalone: false,
  },
  {
    rule: 'v1/reactive-dispatch-unresolved',
    dir: 'reactive-dispatch-unresolved',
    code: 'SC9012',
    severity: 'warning',
    category: limitsV1,
    summary: 'A call can reach implementations with different reactivity, so its behaviour cannot be pinned down.',
    alsoReports: ['SC4002'],
  },
];

export const EXAMPLES_BY_DIALECT: Record<Dialect, readonly ExampleEntry[]> = {
  'solid-v1': SOLID_V1_EXAMPLES,
  'solid-v2': SOLID_V2_EXAMPLES,
};
